name: Guilds
author: Jacksonnn
version: BETA v1.0
main: com.jacksonnn.guilds.GuildsMain
commands:
  guilds:
    aliases: [g, guild]
    usage: /<command>
    description: GuildsMain at it's finest... (Not really)!
